### ISSUE TITLE
In game lag

### ISSUE THREAD

**Issue by ScruffyDoge** [Palmidence/Toontown#1]
my PC definitely meets all of the recommended specs, but yet i run 10-15 fps in playgrounds and 40 in my estate. can i fix this or is this an optimization thing that the devs need to fix?

**Comment by FileStream** [comment]
Definitely optimization. How does your fps change when you enter an area with a low amount of people such as a street?

**Comment by Palmidence** [comment]
I've experienced this frequently. The optimization is within the developer's hands- I've noticed a lot of complaints regarding lag, and the lag disappears once on a street or inside a building during a task. Whenever there's more players rendered, the framerate takes a nosedive.

I believe the developers are aware.

**Comment by ScruffyDoge** [comment]
I didn't get a chance to enter any streets cause the servers have been off and on. I'll update as soon as I can

**Comment by ScruffyDoge** [comment]
@FileStream Game runs fine in HQ and Estate.

**Comment by FileStream** [comment]
@ScruffyDoge Good to hear. Closing issue.
